# name: Visitor Simulation Automation

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   simulate-visitors:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         batch: [1, 2, 3, 4, 5] # Process in 5 batches

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.10'

#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#         playwright install-deps
#         playwright install

#     - name: Run Visitor Simulation for Batch ${{ matrix.batch }}
#       run: xvfb-run --auto-servernum -- python server.py --batch ${{ matrix.batch }}











name: Visitor Simulation Automation

on:
  workflow_dispatch: # Allows manual start
  schedule:
    - cron: "*/30 * * * *" # Triggers every 30 minutes

concurrency:
  group: simulate-visitors
  cancel-in-progress: false # Ensures no overlapping workflows

jobs:
  simulate-visitors:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: [1, 2, 3, 4, 5] # Process in 5 batches

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install-deps
        playwright install

    - name: Run Visitor Simulation for Batch ${{ matrix.batch }}
      run: xvfb-run --auto-servernum -- python server.py --batch ${{ matrix.batch }}

  delay-between-runs:
    runs-on: ubuntu-latest
    needs: simulate-visitors # Waits for all batches to complete
    steps:
    - name: Add Random Delay
      run: |
        DELAY=$((30 + RANDOM % 21)) # Random delay between 30 and 50 minutes
        echo "Sleeping for $DELAY minutes..."
        sleep $((DELAY * 60))
